# -*- coding: utf-8 -*-
"""python prc

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zu62WDhnEziNEM_CkoB4fGnXzvBvpjTA
"""

a=int(input("enter a number"))
if a%2==0:
  print("even")
else:
  print("odd")

a=int(input("enter a number: "))
count=0
for i in range(2,a):
  if(a%i==0):
     print("not prime")
     count=count+1
if(count==0):
 print("prime")

